# -*- coding: utf-8 -*-
"""扩展批次 P4：科学方法论思想家（费曼/达尔文/爱因斯坦/牛顿/香农/图灵/培根/笛卡尔）"""

POWERS_P4 = [
# ---------- 理查德·费曼 ----------
{"id":"feynman_01","knowledge":"第一性原理：从基本原理出发推导，不依赖类比与惯例。商业启示：问『这件事的本质约束是什么』，从约束反推方案，别用『大家都这么做』当理由。","original":"理查德·费曼《费曼物理学讲义》","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1964","topics":["决策","创新"],"skills":["poe-good-question","poe-decision","poe-deconstruct"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"feynman_02","knowledge":"费曼技巧：讲不清就是没真懂。商业启示：检验自己是否理解一个业务问题，尝试用最简单的语言向新手讲清楚，卡住的地方就是认知缺口。","original":"理查德·费曼（教学方法）","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1985","topics":["学习","认知"],"skills":["poe-learning","poe-good-question","poe-ai-check"],"type":"method","confidence":"high","audience":"🔬🔥"},
{"id":"feynman_03","knowledge":"科学诚实：记录所有数据，包括不利的证据。商业启示：复盘、实验、A/B 测试要保留失败数据，只讲成功故事的团队在系统性自我欺骗。","original":"理查德·费曼《别闹了，费曼先生》","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1985","topics":["决策","组织"],"skills":["poe-verify","poe-decision","poe-ai-check"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"feynman_04","knowledge":"简化：复杂现象背后必有简单规律。商业启示：业务看不懂时不要先加概念，先寻找能解释大部分现象的最小机制。","original":"理查德·费曼《费曼物理学讲义》","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1964","topics":["认知","决策"],"skills":["poe-deconstruct","poe-diagnosis","poe-good-question"],"type":"insight","confidence":"high","audience":"🔬💼"},
{"id":"feynman_05","knowledge":"『我不知道』是力量的来源：承认无知才有资格开始研究。商业启示：敢说不知道的团队才能校准认知，假装知道的团队会在错误上叠加错误。","original":"理查德·费曼《别闹了，费曼先生》","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1985","topics":["认知","心态"],"skills":["poe-good-question","poe-verify","poe-decision"],"type":"principle","confidence":"high","audience":"🔬"},
{"id":"feynman_06","knowledge":"好奇心驱动：为问题本身着迷，而非为结果奖励。商业启示：招人看好奇心，自驱的人在无人监督时仍会探索；强 KPI 驱动会杀死好奇。","original":"理查德·费曼《别闹了，费曼先生》","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1985","topics":["组织","激励"],"skills":["poe-action","poe-decision","poe-goal"],"type":"principle","confidence":"medium","audience":"💼"},
{"id":"feynman_07","knowledge":"不确定性是科学的一部分：承认测量与预测有误差。商业启示：给所有预测加误差带，『大概正确』好过『精确错误』。","original":"理查德·费曼《费曼物理学讲义》","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1964","topics":["决策","认知"],"skills":["poe-verify","poe-decision","poe-ai-check"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"feynman_08","knowledge":"解构式学习：从最简单的例子开始，逐步逼近复杂。商业启示：学新业务、新市场从最小案例切入，先跑通最小闭环再谈规模。","original":"理查德·费曼（教学方法）","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1985","topics":["学习","决策"],"skills":["poe-learning","poe-good-question","poe-goal"],"type":"method","confidence":"high","audience":"🔬"},
{"id":"feynman_09","knowledge":"批判权威：权威不自动等于正确。商业启示：大厂方案、行业报告、专家观点都要回到证据本身，职称与头衔不是证据。","original":"理查德·费曼《别闹了，费曼先生》","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1985","topics":["认知","决策"],"skills":["poe-verify","poe-deconstruct","poe-standard-answer"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"feynman_10","knowledge":"犯错的价值：科学是试错过程，错误是信息。商业启示：把失败当数据采集而不是耻辱，快速小成本试错是唯一合法的犯错方式。","original":"理查德·费曼《别闹了，费曼先生》","url":"https://zh.wikipedia.org/wiki/理查德·费曼","date":"1985","topics":["创新","心态"],"skills":["poe-action","poe-slowisfast","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},

# ---------- 查尔斯·达尔文 ----------
{"id":"darwin_01","knowledge":"变异-选择-遗传：演化的三要素。商业启示：组织要持续产生变异（试验）、强选择（淘汰）、沉淀（固化），三者缺一就无法适应环境。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["组织","创新"],"skills":["poe-diagnosis","poe-standard-answer","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"darwin_02","knowledge":"适应是相对的：生存下来的不是最强，而是最适应当前环境。商业启示：别迷信『强者』叙事，环境一变，适应性弱的巨头也会倒下。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["战略","市场"],"skills":["poe-standard-answer","poe-diagnosis","poe-benchmark"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"darwin_03","knowledge":"红皇后效应：你必须不断奔跑才能留在原地。商业启示：在激烈竞争生态里，维持现状本身就是衰退，增速是生存参数而非虚荣指标。","original":"刘易斯·卡罗尔《爱丽丝镜中奇遇》（演化生物学概念）","url":"https://zh.wikipedia.org/wiki/红皇后假说","date":"1871","topics":["战略","市场"],"skills":["poe-standard-answer","poe-slowisfast","poe-benchmark"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"darwin_04","knowledge":"生态位：每个物种占据独特生态位，竞争越少活得越稳。商业启示：找不到差异化位置就活在同质竞争里，先找『只有我能占』的生态位。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["战略","市场"],"skills":["poe-benchmark","poe-diagnosis","poe-standard-answer"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"darwin_05","knowledge":"多样性是保险：种群多样性保障环境剧变时的存活。商业启示：产品线、人才、现金流的多样性是应对不确定性的保险，别把所有鸡蛋放进单一最优解。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["组织","风险"],"skills":["poe-decision","poe-diagnosis","poe-verify"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"darwin_06","knowledge":"渐进式改变：巨大变化由微小变化累积而成。商业启示：转型不必推倒重来，每天改进一点的组织最终甩开等待『大招』的对手。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["组织","创新"],"skills":["poe-slowisfast","poe-action","poe-goal"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"darwin_07","knowledge":"共同祖先：看似无关的物种共享演化起源。商业启示：行业里的头部玩家共享同一套演化逻辑，研究彼此的祖先路径能预判下一步。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["战略","商业模式"],"skills":["poe-standard-answer","poe-benchmark","poe-diagnosis"],"type":"insight","confidence":"medium","audience":"🔬💼"},
{"id":"darwin_08","knowledge":"自然选择只留适应者：适应是事后被环境选出来的，不是事前计划好的。商业启示：方向感很重要，但最终活下来的业务是环境筛选的结果，保持选项开放。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["战略","决策"],"skills":["poe-standard-answer","poe-decision","poe-verify"],"type":"principle","confidence":"medium","audience":"🔬💼"},
{"id":"darwin_09","knowledge":"竞争与共生并存：生态不只是丛林法则，互惠关系同样普遍。商业启示：供应链、平台与生态伙伴的关系是共生结构，把合作方当物种而非猎物。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["市场","组织"],"skills":["poe-diagnosis","poe-standard-answer","poe-decision"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"darwin_10","knowledge":"演化没有完美终点：物种永远在适应路上。商业启示：没有『做完』的产品和『到位』的组织，适应是持续过程，自满即淘汰开始。","original":"查尔斯·达尔文《物种起源》","url":"https://zh.wikipedia.org/wiki/查尔斯·达尔文","date":"1859","topics":["心态","组织"],"skills":["poe-slowisfast","poe-action","poe-goal"],"type":"principle","confidence":"high","audience":"💼"},

# ---------- 阿尔伯特·爱因斯坦 ----------
{"id":"einstein_01","knowledge":"想象力比知识更重要：知识有边界，想象覆盖可能。商业启示：规划未来业务时先放开想象再收束到可行，只从现有知识推演会错过非连续机会。","original":"阿尔伯特·爱因斯坦（演讲）","url":"https://zh.wikipedia.org/wiki/阿尔伯特·爱因斯坦","date":"1929","topics":["创新","认知"],"skills":["poe-good-question","poe-standard-answer","poe-decision"],"type":"principle","confidence":"medium","audience":"🔬"},
{"id":"einstein_02","knowledge":"尽可能简单，但不能更简单：简化有底线。商业启示：把业务简化到核心是本事，但过度简化会丢掉关键变量，简化到『仍能解释全部现象』为止。","original":"阿尔伯特·爱因斯坦（方法论）","url":"https://zh.wikipedia.org/wiki/阿尔伯特·爱因斯坦","date":"1933","topics":["认知","决策"],"skills":["poe-deconstruct","poe-good-question","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"einstein_03","knowledge":"好的问题已解决一半：提问方式决定答案空间。商业启示：花时间把问题本身打磨清楚，问对问题比猛做答案省十倍成本。","original":"阿尔伯特·爱因斯坦（方法论）","url":"https://zh.wikipedia.org/wiki/阿尔伯特·爱因斯坦","date":"1933","topics":["决策","认知"],"skills":["poe-good-question","poe-goal","poe-decision"],"type":"method","confidence":"high","audience":"🔬💼"},
{"id":"einstein_04","knowledge":"教育是忘掉后剩下的：真正的学习是内化的思维习惯。商业启示：培训的价值不在记住知识，而在改变行为习惯，检验方式是三个月后还在用的那部分。","original":"阿尔伯特·爱因斯坦（语录）","url":"https://zh.wikipedia.org/wiki/阿尔伯特·爱因斯坦","date":"1921","topics":["学习","组织"],"skills":["poe-learning","poe-action","poe-goal"],"type":"insight","confidence":"medium","audience":"🔬"},
{"id":"einstein_05","knowledge":"质疑理所当然：『为什么是这样』比『是不是这样』更有价值。商业启示：定期质疑行业默认前提，被质疑的前提里常藏着机会与陷阱。","original":"阿尔伯特·爱因斯坦（方法论）","url":"https://zh.wikipedia.org/wiki/阿尔伯特·爱因斯坦","date":"1933","topics":["创新","认知"],"skills":["poe-deconstruct","poe-good-question","poe-verify"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"einstein_06","knowledge":"我并没有失败，只是发现了上万种行不通的方式。商业启示：把失败重命名为『排除法进度』，试错心态决定团队能否熬过探索期。","original":"阿尔伯特·爱因斯坦（语录）","url":"https://zh.wikipedia.org/wiki/阿尔伯特·爱因斯坦","date":"1930","topics":["心态","创新"],"skills":["poe-action","poe-slowisfast","poe-goal"],"type":"principle","confidence":"high","audience":"🔥"},
{"id":"einstein_07","knowledge":"相对性：观察者的状态影响判断结果。商业启示：同一业务数据，不同立场的人读出不同结论，复盘时先声明自己的位置再谈判断。","original":"阿尔伯特·爱因斯坦《狭义相对论》","url":"https://zh.wikipedia.org/wiki/阿尔伯特·爱因斯坦","date":"1905","topics":["认知","决策"],"skills":["poe-verify","poe-deconstruct","poe-decision"],"type":"insight","confidence":"medium","audience":"🔬💼"},
{"id":"einstein_08","knowledge":"直觉与逻辑互补：发现靠直觉，验证靠逻辑。商业启示：点子可以凭直觉产生，但上规模之前必须过逻辑与数据验证关，两者缺一都是半吊子。","original":"阿尔伯特·爱因斯坦（方法论）","url":"https://zh.wikipedia.org/wiki/阿尔伯特·爱因斯坦","date":"1933","topics":["决策","创新"],"skills":["poe-decision","poe-verify","poe-good-question"],"type":"insight","confidence":"high","audience":"🔬💼"},

# ---------- 艾萨克·牛顿 ----------
{"id":"newton_01","knowledge":"站在巨人肩上：承认并利用前人的积累。商业启示：别重复发明轮子，行业成熟方法、开源工具、已验证框架先拿来用，把稀缺精力留给真正的增量。","original":"艾萨克·牛顿（致胡克书信）","url":"https://zh.wikipedia.org/wiki/艾萨克·牛顿","date":"1676","topics":["创新","决策"],"skills":["poe-standard-answer","poe-benchmark","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"newton_02","knowledge":"统一性：天上地下的规律是同一个。商业启示：别把线上/线下、大客户/小客户当成不同物理世界，同一套规律能解释看似无关的现象时，你就接近本质了。","original":"艾萨克·牛顿《自然哲学的数学原理》","url":"https://zh.wikipedia.org/wiki/艾萨克·牛顿","date":"1687","topics":["认知","决策"],"skills":["poe-deconstruct","poe-standard-answer","poe-diagnosis"],"type":"principle","confidence":"medium","audience":"🔬"},
{"id":"newton_03","knowledge":"惯性：物体状态需要外力才能改变。商业启示：组织、业务、习惯都有惯性，推进变革必须持续施加作用力，一次动员会改变不了运动状态。","original":"艾萨克·牛顿《自然哲学的数学原理》","url":"https://zh.wikipedia.org/wiki/艾萨克·牛顿","date":"1687","topics":["组织","管理"],"skills":["poe-action","poe-slowisfast","poe-goal"],"type":"insight","confidence":"high","audience":"💼"},
{"id":"newton_04","knowledge":"作用力与反作用力：每个作用都有相等的反作用。商业启示：强推政策必遭反弹，砍预算、压工期、强制考核的反作用力与力度成正比，设计变革先算反作用账。","original":"艾萨克·牛顿《自然哲学的数学原理》","url":"https://zh.wikipedia.org/wiki/艾萨克·牛顿","date":"1687","topics":["组织","管理"],"skills":["poe-diagnosis","poe-decision","poe-action"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"newton_05","knowledge":"假设不作伪（Hypotheses non fingo）：不编造无法检验的假设。商业启示：写商业计划时区分『可验证假设』与『无法证伪的漂亮话』，后者只是修辞。","original":"艾萨克·牛顿《自然哲学的数学原理》","url":"https://zh.wikipedia.org/wiki/艾萨克·牛顿","date":"1687","topics":["决策","认知"],"skills":["poe-verify","poe-good-question","poe-ai-check"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"newton_06","knowledge":"专注与耐心：持续思考同一问题直到想通。商业启示：真正难的问题需要长期浸泡，频繁换赛道的组织永远达不到深度，深度是时间的函数。","original":"艾萨克·牛顿（生平记载）","url":"https://zh.wikipedia.org/wiki/艾萨克·牛顿","date":"1687","topics":["心态","学习"],"skills":["poe-slowisfast","poe-learning","poe-goal"],"type":"method","confidence":"medium","audience":"🔬💼"},

# ---------- 克劳德·香农 ----------
{"id":"shannon_01","knowledge":"信息熵：信息量等于不确定性的减少。商业启示：汇报与数据要问『这条信息减少了什么不确定性』，不减少不确定性的信息是噪声。","original":"克劳德·香农《通信的数学理论》","url":"https://zh.wikipedia.org/wiki/克劳德·香农","date":"1948","topics":["信息","决策"],"skills":["poe-good-question","poe-decision","poe-ai-check"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"shannon_02","knowledge":"信道容量：任何信道都有信息传输上限，超过即失真。商业启示：组织带宽、注意力、传播渠道都有容量，硬塞信息只会造成失真与误读。","original":"克劳德·香农《通信的数学理论》","url":"https://zh.wikipedia.org/wiki/克劳德·香农","date":"1948","topics":["信息","组织"],"skills":["poe-content","poe-good-question","poe-ai-check"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"shannon_03","knowledge":"冗余对抗噪声：编码加入冗余信息以纠错。商业启示：品牌、流程、关键节点要留冗余（备选方案、备份数据、多通道触达），纯最优化设计在噪声面前很脆。","original":"克劳德·香农《通信的数学理论》","url":"https://zh.wikipedia.org/wiki/克劳德·香农","date":"1948","topics":["风险","组织","内容"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"shannon_04","knowledge":"信息不等于意义：信息是符号层面，意义是解释层面。商业启示：数据堆积不等于洞察，同样的数据可以支撑相反结论，解释框架决定一切。","original":"克劳德·香农《通信的数学理论》","url":"https://zh.wikipedia.org/wiki/克劳德·香农","date":"1948","topics":["信息","认知"],"skills":["poe-ai-check","poe-deconstruct","poe-verify"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"shannon_05","knowledge":"业余者跨界：香农以『业余者』身份用数学统一了通信理论。商业启示：跨领域视角常带来降维打击，招人与学习都要拥抱『外行的新鲜感』。","original":"克劳德·香农（生平）","url":"https://zh.wikipedia.org/wiki/克劳德·香农","date":"1948","topics":["创新","学习"],"skills":["poe-standard-answer","poe-learning","poe-good-question"],"type":"insight","confidence":"medium","audience":"🔬"},
{"id":"shannon_06","knowledge":"最小模型：香农把复杂通信问题简化为信源-信道-信宿模型。商业启示：为业务建立最小可解释模型（输入-机制-输出），模型简洁度与理解深度正相关。","original":"克劳德·香农《通信的数学理论》","url":"https://zh.wikipedia.org/wiki/克劳德·香农","date":"1948","topics":["认知","决策"],"skills":["poe-deconstruct","poe-diagnosis","poe-good-question"],"type":"method","confidence":"high","audience":"🔬💼"},
{"id":"shannon_07","knowledge":"一切皆可量化：比特统一了文字、图像、声音。商业启示：把不可比的东西（体验、口碑、流程）量化成指标，才能被管理，量化是改善的第一步。","original":"克劳德·香农（信息论应用）","url":"https://zh.wikipedia.org/wiki/克劳德·香农","date":"1948","topics":["管理","决策"],"skills":["poe-goal","poe-diagnosis","poe-decision"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"shannon_08","knowledge":"通信三问：谁在说话、对谁说话、通过什么信道。商业启示：做内容与传播先回答这三问，说不清受众与信道的传播是自嗨。","original":"克劳德·香农（通信模型引申）","url":"https://zh.wikipedia.org/wiki/克劳德·香农","date":"1948","topics":["内容","传播"],"skills":["poe-content","poe-spread","poe-resonate"],"type":"method","confidence":"high","audience":"🔥💼"},

# ---------- 艾伦·图灵 ----------
{"id":"turing_01","knowledge":"可计算性边界：不是所有问题都能用算法求解。商业启示：识别问题的『算法不可解部分』（如真正的用户偏好、创造力），别把全部业务都交给确定性流程。","original":"艾伦·图灵《论可计算数》","url":"https://zh.wikipedia.org/wiki/艾伦·图灵","date":"1936","topics":["决策","认知"],"skills":["poe-decision","poe-good-question","poe-deconstruct"],"type":"principle","confidence":"high","audience":"🔬"},
{"id":"turing_02","knowledge":"图灵测试：以行为判断智能，而不是内部机制。商业启示：用户只看结果体验，不关心你内部怎么实现，把评判标准对准『用户可观察的行为结果』。","original":"艾伦·图灵《计算机器与智能》","url":"https://zh.wikipedia.org/wiki/艾伦·图灵","date":"1950","topics":["产品","认知"],"skills":["poe-diagnosis","poe-good-question","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"turing_03","knowledge":"简单性中的通用性：图灵机只有最简单规则却能力无限。商业启示：强大的系统可以建立在极简规则上，设计组织与产品先找最小规则集。","original":"艾伦·图灵《论可计算数》","url":"https://zh.wikipedia.org/wiki/艾伦·图灵","date":"1936","topics":["认知","组织"],"skills":["poe-deconstruct","poe-diagnosis","poe-decision"],"type":"insight","confidence":"high","audience":"🔬💼"},
{"id":"turing_04","knowledge":"把问题当编码问题：图灵破译恩尼格玛密码机，靠的是结构分析与系统思维。商业启示：看似无解的商业谜题，换一个『编码-解码』视角常能找到突破口。","original":"艾伦·图灵（二战密码破译）","url":"https://zh.wikipedia.org/wiki/艾伦·图灵","date":"1945","topics":["决策","创新"],"skills":["poe-standard-answer","poe-good-question","poe-decision"],"type":"method","confidence":"medium","audience":"🔬💼"},
{"id":"turing_05","knowledge":"机器可以学习：图灵预言机器能通过学习改善自身。商业启示：组织也要有学习机制——复盘、反馈回路、知识沉淀，不会学习的组织会被会学习的取代。","original":"艾伦·图灵《计算机器与智能》","url":"https://zh.wikipedia.org/wiki/艾伦·图灵","date":"1950","topics":["组织","学习"],"skills":["poe-learning","poe-knowledge","poe-content-system"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"turing_06","knowledge":"模仿游戏：智能的判定是能否成功模仿人类对话。商业启示：与用户、客户沟通时以『对方能否自然接续』为标准检验理解，而不是自认为表达清楚了。","original":"艾伦·图灵《计算机器与智能》","url":"https://zh.wikipedia.org/wiki/艾伦·图灵","date":"1950","topics":["沟通","产品"],"skills":["poe-content","poe-good-question","poe-resonate"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"turing_07","knowledge":"机器能思考吗：问题的问法本身就是革命。商业启示：行业里的『不可能问题』换个问法常变成可解问题，重定义问题是创新捷径。","original":"艾伦·图灵《计算机器与智能》","url":"https://zh.wikipedia.org/wiki/艾伦·图灵","date":"1950","topics":["创新","认知"],"skills":["poe-good-question","poe-deconstruct","poe-standard-answer"],"type":"insight","confidence":"high","audience":"🔬💼"},
{"id":"turing_08","knowledge":"早逝与边缘：图灵因性取向被摧残致死，天才也会被偏见毁掉。商业启示：组织的包容度直接决定它能否留住天才，歧视的代价是系统性人才损失。","original":"艾伦·图灵（生平）","url":"https://zh.wikipedia.org/wiki/艾伦·图灵","date":"1954","topics":["组织","价值观"],"skills":["poe-diagnosis","poe-action","poe-standard-answer"],"type":"insight","confidence":"high","audience":"⚠️💼"},

# ---------- 弗朗西斯·培根 ----------
{"id":"bacon_01","knowledge":"四假象说：部落假象（人类共性偏见）、洞穴假象（个人视角）、市场假象（语言滥用）、剧场假象（权威迷信）。商业启示：做判断前先自查这四类偏见源，团队会议尤其要防市场假象与剧场假象。","original":"弗朗西斯·培根《新工具》","url":"https://zh.wikipedia.org/wiki/弗朗西斯·培根","date":"1620","topics":["认知","决策"],"skills":["poe-verify","poe-deconstruct","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"bacon_02","knowledge":"归纳法：知识从经验观察中来，而非从权威演绎。商业启示：决策依据要回到一手数据与现场观察，二手转述与行业传言只能当线索。","original":"弗朗西斯·培根《新工具》","url":"https://zh.wikipedia.org/wiki/弗朗西斯·培根","date":"1620","topics":["决策","认知"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"method","confidence":"high","audience":"🔬💼"},
{"id":"bacon_03","knowledge":"知识就是力量：控制知识的人控制结果。商业启示：信息与专业能力是组织真正的权力来源，别把知识集中在少数人手里，要制度化。","original":"弗朗西斯·培根《新工具》","url":"https://zh.wikipedia.org/wiki/弗朗西斯·培根","date":"1620","topics":["组织","价值观"],"skills":["poe-knowledge","poe-content-system","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"bacon_04","knowledge":"实验优于争论：一个实验胜过千次辩论。商业启示：团队争论不下时立刻设计最小实验，用数据终止口舌之战。","original":"弗朗西斯·培根《新工具》","url":"https://zh.wikipedia.org/wiki/弗朗西斯·培根","date":"1620","topics":["决策","组织"],"skills":["poe-decision","poe-good-question","poe-verify"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"bacon_05","knowledge":"先清空偏见再观察：带着预设立场看到的世界只是自我的投影。商业启示：做市场调研前先写下自己的预期，防止把调研做成自我确认。","original":"弗朗西斯·培根《新工具》","url":"https://zh.wikipedia.org/wiki/弗朗西斯·培根","date":"1620","topics":["认知","决策"],"skills":["poe-verify","poe-good-question","poe-ai-check"],"type":"method","confidence":"high","audience":"🔬💼"},
{"id":"bacon_06","knowledge":"渐进积累：科学是集体积累而非个人顿悟。商业启示：组织能力靠制度化的积累（文档、复盘、SOP），依赖个人英雄的团队无法累积。","original":"弗朗西斯·培根《新工具》","url":"https://zh.wikipedia.org/wiki/弗朗西斯·培根","date":"1620","topics":["组织","学习"],"skills":["poe-knowledge","poe-content-system","poe-slowisfast"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"bacon_07","knowledge":"怀疑传统权威：传统与权威必须接受经验检验。商业启示：『一直这么做的』不是有效论证，用数据重新检验每一个历史惯例。","original":"弗朗西斯·培根《新工具》","url":"https://zh.wikipedia.org/wiki/弗朗西斯·培根","date":"1620","topics":["认知","创新"],"skills":["poe-verify","poe-deconstruct","poe-standard-answer"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"bacon_08","knowledge":"知识的目的：为人类生活谋福利，而非空谈。商业启示：知识资产必须连接到实际产出，衡量知识的价值看它改变了什么行动。","original":"弗朗西斯·培根《新大西岛》","url":"https://zh.wikipedia.org/wiki/弗朗西斯·培根","date":"1627","topics":["价值观","组织"],"skills":["poe-goal","poe-action","poe-knowledge"],"type":"principle","confidence":"medium","audience":"💼"},

# ---------- 勒内·笛卡尔 ----------
{"id":"descartes_01","knowledge":"方法论的怀疑：怀疑一切可怀疑的，直到找到不可怀疑的基点。商业启示：业务假设要逐一质疑，直到找到『不依赖任何假设也能成立』的核心。","original":"勒内·笛卡尔《谈谈方法》","url":"https://zh.wikipedia.org/wiki/勒内·笛卡尔","date":"1637","topics":["决策","认知"],"skills":["poe-verify","poe-deconstruct","poe-good-question"],"type":"method","confidence":"high","audience":"🔬💼"},
{"id":"descartes_02","knowledge":"我思故我在：从第一个确定点出发建立体系。商业启示：战略思考要有『确定的第一块砖』（不变的用户需求、核心能力），其余从它推出。","original":"勒内·笛卡尔《谈谈方法》","url":"https://zh.wikipedia.org/wiki/勒内·笛卡尔","date":"1637","topics":["决策","战略"],"skills":["poe-decision","poe-good-question","poe-goal"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"descartes_03","knowledge":"分割问题：把复杂问题拆到不可再分的最小单位。商业启示：大问题看着无解，拆到最小单元后每个都可行动，拆解粒度决定执行力。","original":"勒内·笛卡尔《谈谈方法》","url":"https://zh.wikipedia.org/wiki/勒内·笛卡尔","date":"1637","topics":["决策","组织"],"skills":["poe-good-question","poe-goal","poe-decision"],"type":"method","confidence":"high","audience":"💼"},
{"id":"descartes_04","knowledge":"从简到繁：按顺序从最容易的开始推理。商业启示：推进复杂项目先做最简单的闭环，逐步叠加复杂度，别一上来就啃最难的模块。","original":"勒内·笛卡尔《谈谈方法》","url":"https://zh.wikipedia.org/wiki/勒内·笛卡尔","date":"1637","topics":["决策","项目管理"],"skills":["poe-goal","poe-action","poe-decision"],"type":"method","confidence":"high","audience":"💼"},
{"id":"descartes_05","knowledge":"全面枚举：检查是否有遗漏。商业启示：做方案清单后专门做『遗漏检查』（还有什么没考虑），遗漏的往往是最致命的变量。","original":"勒内·笛卡尔《谈谈方法》","url":"https://zh.wikipedia.org/wiki/勒内·笛卡尔","date":"1637","topics":["决策"],"skills":["poe-good-question","poe-verify","poe-decision"],"type":"method","confidence":"high","audience":"🔬💼"},
{"id":"descartes_06","knowledge":"清晰明确的标准：凡清晰明确的观念才可信。商业启示：警惕模糊表达——『大概』『差不多』『市场会接受』，把每个关键概念逼到清晰定义再继续。","original":"勒内·笛卡尔《第一哲学沉思集》","url":"https://zh.wikipedia.org/wiki/勒内·笛卡尔","date":"1641","topics":["认知","决策"],"skills":["poe-deconstruct","poe-good-question","poe-ai-check"],"type":"principle","confidence":"high","audience":"🔬💼"},
]
