# -*- coding: utf-8 -*-
"""扩展批次 P5：社会与经济思想家（亚里士多德/密尔/韦伯/凯恩斯/弗里德曼/熊彼特/索罗斯/格鲁夫）"""

POWERS_P5 = [
# ---------- 亚里士多德 ----------
{"id":"aristotle_01","knowledge":"四因说：理解事物要问四种原因——质料、形式、动力、目的。商业启示：分析业务别只问『怎么做的』，要问到『为什么存在』（目的因），目的不清则其余都是盲目。","original":"亚里士多德《形而上学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["决策","认知"],"skills":["poe-good-question","poe-deconstruct","poe-diagnosis"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"aristotle_02","knowledge":"黄金中道：美德是两个极端之间的适度。商业启示：激进与保守、集权与放权、快与慢——多数管理问题的最优解不在两极而在恰到好处的中间。","original":"亚里士多德《尼各马可伦理学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["决策","价值观"],"skills":["poe-decision","poe-slowisfast","poe-diagnosis"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"aristotle_03","knowledge":"习惯塑造品格：我们反复做的事成就了我们。商业启示：组织的文化不是宣言，是日常重复行为的沉淀；改变习惯比改变口号重要。","original":"亚里士多德《尼各马可伦理学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["组织","心态"],"skills":["poe-action","poe-goal","poe-slowisfast"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"aristotle_04","knowledge":"实践智慧（Phronesis）：在具体情境下做出正确判断的能力。商业启示：案例与规则给不了实践智慧，它来自大量真实情境中的判断练习——多实战、多复盘。","original":"亚里士多德《尼各马可伦理学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["决策","学习"],"skills":["poe-decision","poe-learning","poe-standard-answer"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"aristotle_05","knowledge":"整体大于部分之和：系统的性质不能从孤立部分推出。商业启示：评估团队与产品要看协同，单个强环节凑在一起不一定强，先看衔接。","original":"亚里士多德《形而上学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["组织","认知"],"skills":["poe-diagnosis","poe-decision","poe-deconstruct"],"type":"insight","confidence":"high","audience":"💼"},
{"id":"aristotle_06","knowledge":"修辞三要素：人格（Ethos）、情感（Pathos）、逻辑（Logos）。商业启示：说服靠三者的合力——没有可信度、不触情绪、逻辑再严密也推不动人。","original":"亚里士多德《修辞学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["内容","传播"],"skills":["poe-content","poe-resonate","poe-hook"],"type":"principle","confidence":"high","audience":"🔥💼"},
{"id":"aristotle_07","knowledge":"求知是人的本性：人天然好奇。商业启示：内容与产品满足好奇即获客，『让人想知道答案』是最好的钩子。","original":"亚里士多德《形而上学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["内容","心理"],"skills":["poe-content","poe-hook","poe-resonate"],"type":"principle","confidence":"medium","audience":"🔥"},
{"id":"aristotle_08","knowledge":"人是政治动物：人在共同体中才有完整意义。商业启示：归属感与共同体是组织留人的底层需求，纯雇佣关系留不住长期人才。","original":"亚里士多德《政治学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["组织","价值观"],"skills":["poe-diagnosis","poe-action","poe-goal"],"type":"principle","confidence":"medium","audience":"💼"},
{"id":"aristotle_09","knowledge":"分类学思维：先分类再研究，分类本身就是理解。商业启示：用户、问题、需求先做严格分类，分类粒度决定你能看到什么规律。","original":"亚里士多德（生物分类学）","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["认知","决策"],"skills":["poe-deconstruct","poe-good-question","poe-diagnosis"],"type":"method","confidence":"medium","audience":"🔬💼"},
{"id":"aristotle_10","knowledge":"幸福是活动的卓越：幸福不是状态，是实现潜能的活动。商业启示：员工激励的终局是让工作本身成为卓越活动，外在奖励只是入场券。","original":"亚里士多德《尼各马可伦理学》","url":"https://zh.wikipedia.org/wiki/亚里士多德","date":"公元前350","topics":["激励","价值观"],"skills":["poe-action","poe-goal","poe-diagnosis"],"type":"principle","confidence":"medium","audience":"💼"},

# ---------- 约翰·斯图尔特·密尔 ----------
{"id":"mill_01","knowledge":"功利主义：行动以最大多数人的最大幸福为准则。商业启示：产品与政策评估要算『总福祉账』，局部最优不等于整体最优。","original":"约翰·斯图尔特·密尔《功利主义》","url":"https://zh.wikipedia.org/wiki/约翰·斯图尔特·密尔","date":"1863","topics":["价值观","决策"],"skills":["poe-decision","poe-diagnosis","poe-standard-answer"],"type":"principle","confidence":"medium","audience":"⚠️💼"},
{"id":"mill_02","knowledge":"思想自由市场：言论自由是发现真理的机制，异见必须被容忍。商业启示：团队里消灭反对声等于消灭校准机制，决策前强制请出『魔鬼代言人』。","original":"约翰·斯图尔特·密尔《论自由》","url":"https://zh.wikipedia.org/wiki/约翰·斯图尔特·密尔","date":"1859","topics":["组织","决策"],"skills":["poe-verify","poe-chatroom","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"mill_03","knowledge":"伤害原则：个人自由止于伤害他人。商业启示：设计规则与产品边界时问『会不会伤害他人』，自由与责任是一体两面。","original":"约翰·斯图尔特·密尔《论自由》","url":"https://zh.wikipedia.org/wiki/约翰·斯图尔特·密尔","date":"1859","topics":["价值观","机制设计"],"skills":["poe-content-risk-check","poe-decision","poe-verify"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"mill_04","knowledge":"快乐的质与量：宁做痛苦的苏格拉底，不做满足的猪。商业启示：用户满意度的质量维度与数量维度不同，『上瘾』与『有价值』是两种生意。","original":"约翰·斯图尔特·密尔《功利主义》","url":"https://zh.wikipedia.org/wiki/约翰·斯图尔特·密尔","date":"1863","topics":["价值观","产品"],"skills":["poe-diagnosis","poe-goal","poe-decision"],"type":"principle","confidence":"medium","audience":"⚠️💼"},
{"id":"mill_05","knowledge":"经验主义：一切知识源于经验。商业启示：没有验证过的判断只是猜想，让数据与用户反馈成为知识的唯一来源。","original":"约翰·斯图尔特·密尔《逻辑体系》","url":"https://zh.wikipedia.org/wiki/约翰·斯图尔特·密尔","date":"1843","topics":["认知","决策"],"skills":["poe-verify","poe-decision","poe-good-question"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"mill_06","knowledge":"异见保护真理：即使多数人同意，也必须给异见发声机会。商业启示：把『反对者』当资产——他们是最便宜的防线，别让团队只剩一种声音。","original":"约翰·斯图尔特·密尔《论自由》","url":"https://zh.wikipedia.org/wiki/约翰·斯图尔特·密尔","date":"1859","topics":["组织","决策"],"skills":["poe-verify","poe-chatroom","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"mill_07","knowledge":"自由是进步的引擎：压抑自由的社会会停滞。商业启示：创新需要试错自由，控制欲强的组织短期整齐、长期平庸。","original":"约翰·斯图尔特·密尔《论自由》","url":"https://zh.wikipedia.org/wiki/约翰·斯图尔特·密尔","date":"1859","topics":["创新","组织"],"skills":["poe-diagnosis","poe-standard-answer","poe-action"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"mill_08","knowledge":"女性平等：密尔是议会中最早为女性投票权发声者之一。商业启示：制度性排除某类人才是资源浪费，多样性不只是道德问题，是人才效率问题。","original":"约翰·斯图尔特·密尔《妇女的屈从地位》","url":"https://zh.wikipedia.org/wiki/约翰·斯图尔特·密尔","date":"1869","topics":["价值观","组织"],"skills":["poe-diagnosis","poe-standard-answer","poe-action"],"type":"insight","confidence":"high","audience":"⚠️💼"},

# ---------- 马克斯·韦伯 ----------
{"id":"weber_01","knowledge":"理性化与祛魅：现代社会一切被工具理性支配，神秘与神圣被驱逐。商业启示：数据化、流程化是趋势，但过度工具理性会抽干意义感，员工与用户都需要意义。","original":"马克斯·韦伯《新教伦理与资本主义精神》","url":"https://zh.wikipedia.org/wiki/马克斯·韦伯","date":"1905","topics":["组织","价值观"],"skills":["poe-diagnosis","poe-deconstruct","poe-goal"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"weber_02","knowledge":"官僚制：科层组织高效但也僵化，规则至上会演变为目标置换。商业启示：流程是双刃剑——它保证一致性与可预测，也可能把手段当目的，定期问『这套流程服务什么』。","original":"马克斯·韦伯《经济与社会》","url":"https://zh.wikipedia.org/wiki/马克斯·韦伯","date":"1922","topics":["组织","管理"],"skills":["poe-diagnosis","poe-deconstruct","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"weber_03","knowledge":"新教伦理与资本主义：勤劳、节俭、职业天职观塑造了资本主义精神。商业启示：文化与价值观是经济行为的深层驱动，制度设计脱离文化土壤会水土不服。","original":"马克斯·韦伯《新教伦理与资本主义精神》","url":"https://zh.wikipedia.org/wiki/马克斯·韦伯","date":"1905","topics":["价值观","市场"],"skills":["poe-standard-answer","poe-diagnosis","poe-deconstruct"],"type":"principle","confidence":"medium","audience":"🔬"},
{"id":"weber_04","knowledge":"卡里斯玛权威：魅力型领导的合法性来自个人魅力，但无法制度化传承。商业启示：创始人魅力能开创局面，组织长青要靠把魅力转成制度，否则人走茶凉。","original":"马克斯·韦伯《经济与社会》","url":"https://zh.wikipedia.org/wiki/马克斯·韦伯","date":"1922","topics":["组织","管理"],"skills":["poe-standard-answer","poe-diagnosis","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"weber_05","knowledge":"铁笼：理性化最终把人类关进自己建造的效率牢笼。商业启示：极致效率的组织会丧失适应力与人性，给『低效空间』（闲谈、试错、发呆）留预算。","original":"马克斯·韦伯《新教伦理与资本主义精神》","url":"https://zh.wikipedia.org/wiki/马克斯·韦伯","date":"1905","topics":["组织","价值观"],"skills":["poe-slowisfast","poe-diagnosis","poe-goal"],"type":"principle","confidence":"medium","audience":"⚠️💼"},
{"id":"weber_06","knowledge":"价值中立：学术研究要区分事实判断与价值判断。商业启示：分析报告里『是什么』与『该怎样』分开写，混在一起的分析都是立场先行。","original":"马克斯·韦伯《社会科学方法论》","url":"https://zh.wikipedia.org/wiki/马克斯·韦伯","date":"1904","topics":["认知","决策"],"skills":["poe-ai-check","poe-deconstruct","poe-verify"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"weber_07","knowledge":"理想类型：用简化的理想模型做分析参照。商业启示：『完美客户画像』『理想流程』是分析工具不是现实，用它们做对照找差距，别用它们代替观察。","original":"马克斯·韦伯《社会科学方法论》","url":"https://zh.wikipedia.org/wiki/马克斯·韦伯","date":"1904","topics":["认知","方法"],"skills":["poe-benchmark","poe-deconstruct","poe-diagnosis"],"type":"method","confidence":"high","audience":"🔬💼"},
{"id":"weber_08","knowledge":"责任伦理与信念伦理：政治家应按后果负责（责任伦理），而非只按信念行事。商业启示：决策者要对结果负责，不能拿『我本意是好的』当挡箭牌，评估标准是后果。","original":"马克斯·韦伯《政治作为志业》","url":"https://zh.wikipedia.org/wiki/马克斯·韦伯","date":"1919","topics":["决策","价值观"],"skills":["poe-decision","poe-verify","poe-goal"],"type":"principle","confidence":"high","audience":"💼"},

# ---------- 约翰·梅纳德·凯恩斯 ----------
{"id":"keynes_01","knowledge":"动物精神：投资与经营决策受情绪、直觉与『血性』驱动，而非理性计算。商业启示：市场与团队的情绪周期是真实变量，别假装大家都理性。","original":"约翰·梅纳德·凯恩斯《就业、利息和货币通论》","url":"https://zh.wikipedia.org/wiki/约翰·梅纳德·凯恩斯","date":"1936","topics":["市场","心理"],"skills":["poe-standard-answer","poe-resonate","poe-verify"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"keynes_02","knowledge":"长期来看我们都死了：过度关注长期会忽略当下的现实约束。商业启示：战略要长期，但现金流与生存是当下的硬约束，别用『长期主义』掩盖短期的窟窿。","original":"约翰·梅纳德·凯恩斯《货币改革论》","url":"https://zh.wikipedia.org/wiki/约翰·梅纳德·凯恩斯","date":"1923","topics":["决策","心态"],"skills":["poe-decision","poe-slowisfast","poe-action"],"type":"principle","confidence":"medium","audience":"⚠️💼"},
{"id":"keynes_03","knowledge":"有效需求：总需求不足是经济衰退的直接原因。商业启示：生意萎缩先查需求端——是需求总量没了，还是你的供给没对准需求。","original":"约翰·梅纳德·凯恩斯《就业、利息和货币通论》","url":"https://zh.wikipedia.org/wiki/约翰·梅纳德·凯恩斯","date":"1936","topics":["市场","商业模式"],"skills":["poe-diagnosis","poe-standard-answer","poe-good-question"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"keynes_04","knowledge":"选美理论：市场定价不是选你认为最美的，而是猜别人会选谁。商业启示：传播、定价、趋势判断要理解『共识的共识』——你以为的重要不如大家以为的重要。","original":"约翰·梅纳德·凯恩斯《就业、利息和货币通论》","url":"https://zh.wikipedia.org/wiki/约翰·梅纳德·凯恩斯","date":"1936","topics":["市场","传播"],"skills":["poe-spread","poe-resonate","poe-standard-answer"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"keynes_05","knowledge":"观念的力量：思想最终主导行动，利益次之。商业启示：改变团队与市场先改变观念，认知升级是杠杆最大的投入。","original":"约翰·梅纳德·凯恩斯《就业、利息和货币通论》","url":"https://zh.wikipedia.org/wiki/约翰·梅纳德·凯恩斯","date":"1936","topics":["价值观","组织"],"skills":["poe-content","poe-action","poe-standard-answer"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"keynes_06","knowledge":"黏性：工资与价格短期调整缓慢。商业启示：组织变革与市场反应都有滞后，改革要预留过渡期，别期望一夜之间到位。","original":"约翰·梅纳德·凯恩斯《就业、利息和货币通论》","url":"https://zh.wikipedia.org/wiki/约翰·梅纳德·凯恩斯","date":"1936","topics":["市场","组织"],"skills":["poe-slowisfast","poe-action","poe-decision"],"type":"principle","confidence":"medium","audience":"💼"},
{"id":"keynes_07","knowledge":"不确定性：未来无法概率化，决策靠惯例与信心。商业启示：面对真正的不确定，与其假装精确预测，不如保持现金流与选项的灵活性。","original":"约翰·梅纳德·凯恩斯《就业、利息和货币通论》","url":"https://zh.wikipedia.org/wiki/约翰·梅纳德·凯恩斯","date":"1936","topics":["决策","风险"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"keynes_08","knowledge":"节俭悖论：人人都节俭，总需求下降，经济更差。商业启示：微观理性行为在宏观上可能有害，组织内『局部优化』叠加常导致全局恶化。","original":"约翰·梅纳德·凯恩斯《就业、利息和货币通论》","url":"https://zh.wikipedia.org/wiki/约翰·梅纳德·凯恩斯","date":"1936","topics":["市场","决策"],"skills":["poe-standard-answer","poe-diagnosis","poe-verify"],"type":"insight","confidence":"medium","audience":"⚠️🔬"},

# ---------- 米尔顿·弗里德曼 ----------
{"id":"friedman_01","knowledge":"货币主义：通货膨胀始终且处处是货币现象。商业启示：盯住真正的驱动变量，别被表面原因带偏，找到『货币』级别的根本动因。","original":"米尔顿·弗里德曼《美国货币史》","url":"https://zh.wikipedia.org/wiki/米尔顿·弗里德曼","date":"1963","topics":["市场","决策"],"skills":["poe-diagnosis","poe-standard-answer","poe-verify"],"type":"principle","confidence":"high","audience":"🔬"},
{"id":"friedman_02","knowledge":"自由选择：市场机制在多数情境下优于集中计划。商业启示：内部定价、内部市场（赛马机制）比高层拍板更能配置资源，前提是信息流通顺畅。","original":"米尔顿·弗里德曼《自由选择》","url":"https://zh.wikipedia.org/wiki/米尔顿·弗里德曼","date":"1980","topics":["市场","组织"],"skills":["poe-standard-answer","poe-diagnosis","poe-decision"],"type":"principle","confidence":"medium","audience":"⚠️💼"},
{"id":"friedman_03","knowledge":"永久收入假说：消费基于长期收入预期而非当前收入。商业启示：用户与客户的决策基于预期，经营『预期管理』比经营当下数字重要。","original":"米尔顿·弗里德曼《消费函数理论》","url":"https://zh.wikipedia.org/wiki/米尔顿·弗里德曼","date":"1957","topics":["市场","心理"],"skills":["poe-diagnosis","poe-content","poe-resonate"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"friedman_04","knowledge":"理论的检验标准是预测能力，不是假设的现实性。商业启示：模型『假设不真实』不是问题，预测不准才是；评估判断看它能不能通过事实检验。","original":"米尔顿·弗里德曼《实证经济学方法论》","url":"https://zh.wikipedia.org/wiki/米尔顿·弗里德曼","date":"1953","topics":["决策","认知"],"skills":["poe-verify","poe-ai-check","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"friedman_05","knowledge":"股东至上：企业的社会责任是增加利润。商业启示：警惕用『社会责任』做业绩不佳的遮羞布，先把该做好的基本盘做好。","original":"米尔顿·弗里德曼《纽约时报杂志》","url":"https://zh.wikipedia.org/wiki/米尔顿·弗里德曼","date":"1970","topics":["价值观","商业模式"],"skills":["poe-deconstruct","poe-standard-answer","poe-goal"],"type":"principle","confidence":"low","audience":"⚠️💼"},
{"id":"friedman_06","knowledge":"天下没有免费午餐：任何选择都有成本。商业启示：补贴、免费、优惠都有代价，算清『谁在付钱』，免费只是转移了成本。","original":"米尔顿·弗里德曼（通俗表述）","url":"https://zh.wikipedia.org/wiki/米尔顿·弗里德曼","date":"1975","topics":["决策","商业模式"],"skills":["poe-diagnosis","poe-decision","poe-standard-answer"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"friedman_07","knowledge":"自然失业率：政策无法长期把失业率压到自然水平之下。商业启示：反模式——人为压低某指标（如库存、成本）短期有效，长期会反弹，尊重系统均衡。","original":"米尔顿·弗里德曼《美国货币史》","url":"https://zh.wikipedia.org/wiki/米尔顿·弗里德曼","date":"1968","topics":["市场","决策"],"skills":["poe-decision","poe-standard-answer","poe-verify"],"type":"principle","confidence":"high","audience":"🔬"},
{"id":"friedman_08","knowledge":"负所得税：直接现金补贴比复杂福利系统更有效。商业启示：激励设计要简单直接，复杂的规则网（各种福利、提成、补贴）制造寻租与扭曲。","original":"米尔顿·弗里德曼《资本主义与自由》","url":"https://zh.wikipedia.org/wiki/米尔顿·弗里德曼","date":"1962","topics":["机制设计","激励"],"skills":["poe-diagnosis","poe-goal","poe-decision"],"type":"method","confidence":"medium","audience":"⚠️💼"},

# ---------- 约瑟夫·熊彼特 ----------
{"id":"schumpeter_01","knowledge":"创造性破坏：创新不断摧毁旧结构、创造新结构。商业启示：行业领先地位是暂时的，永远有创新者在拆你的台，保持创新是生存不是选择。","original":"约瑟夫·熊彼特《资本主义、社会主义与民主》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1942","topics":["创新","市场"],"skills":["poe-standard-answer","poe-diagnosis","poe-benchmark"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"schumpeter_02","knowledge":"企业家精神：创新的主体是企业家，是『新组合』的执行者。商业启示：组织要识别并保护企业家型人才——他们不安于现状、不断组合新资源。","original":"约瑟夫·熊彼特《经济发展理论》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1911","topics":["创新","组织"],"skills":["poe-diagnosis","poe-action","poe-standard-answer"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"schumpeter_03","knowledge":"创新五形态：新产品、新方法、新市场、新供应来源、新组织形式。商业启示：创新不只有新技术，五个方向都是突破口，多数人只盯着第一种。","original":"约瑟夫·熊彼特《经济发展理论》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1911","topics":["创新","战略"],"skills":["poe-good-question","poe-standard-answer","poe-benchmark"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"schumpeter_04","knowledge":"利润是创新租金：超额利润来自暂时性创新优势，竞争会把它抹平。商业启示：利润是创新的奖励凭证，停止创新利润就消失，别把租金当永续。","original":"约瑟夫·熊彼特《经济发展理论》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1911","topics":["商业模式","创新"],"skills":["poe-standard-answer","poe-diagnosis","poe-benchmark"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"schumpeter_05","knowledge":"经济周期：创新浪潮的集群出现驱动经济起伏。商业启示：行业有周期是常态，周期低谷是创新者入场的最好时机。","original":"约瑟夫·熊彼特《经济周期》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1939","topics":["市场","战略"],"skills":["poe-standard-answer","poe-decision","poe-slowisfast"],"type":"principle","confidence":"medium","audience":"💼"},
{"id":"schumpeter_06","knowledge":"创新非发明：发明到商业化落地才是创新。商业启示：专利与技术不等于竞争力，能上量、能赚钱、能改变市场才算创新完成。","original":"约瑟夫·熊彼特《经济发展理论》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1911","topics":["创新","决策"],"skills":["poe-decision","poe-good-question","poe-diagnosis"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"schumpeter_07","knowledge":"大企业创新悖论：成功组织官僚化后抑制创新。商业启示：规模带来的流程化会扼杀冒险，大组织要靠独立小团队或外部创新保持活力。","original":"约瑟夫·熊彼特《资本主义、社会主义与民主》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1942","topics":["组织","创新"],"skills":["poe-diagnosis","poe-standard-answer","poe-action"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"schumpeter_08","knowledge":"信贷与创新：银行信用是企业家获取创新资源的通道。商业启示：创新需要资本通道，融资能力与创新能力同等重要，别让好项目死于资金断供。","original":"约瑟夫·熊彼特《经济发展理论》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1911","topics":["商业模式","创新"],"skills":["poe-diagnosis","poe-decision","poe-standard-answer"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"schumpeter_09","knowledge":"企业家与资本家功能分离：创新的执行者不一定是资本的拥有者。商业启示：组织里『出钱的人』与『做事的人』要分开激励，股权设计要覆盖真正的创新执行者。","original":"约瑟夫·熊彼特《经济发展理论》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1911","topics":["组织","激励"],"skills":["poe-diagnosis","poe-decision","poe-goal"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"schumpeter_10","knowledge":"资本主义终结论：资本主义的成功会腐蚀其自身的制度基础。商业启示：反模式——成功的组织会积累保守性并最终僵化，警惕『成功后的傲慢』。","original":"约瑟夫·熊彼特《资本主义、社会主义与民主》","url":"https://zh.wikipedia.org/wiki/约瑟夫·熊彼特","date":"1942","topics":["价值观","战略"],"skills":["poe-standard-answer","poe-diagnosis","poe-slowisfast"],"type":"insight","confidence":"low","audience":"⚠️🔬"},

# ---------- 乔治·索罗斯 ----------
{"id":"soros_01","knowledge":"反身性：认知改变现实，现实改变认知，两者相互反馈。商业启示：在强反馈的市场里（传播、金融、平台），『主流叙事』本身就是变量，别只研究基本面。","original":"乔治·索罗斯《金融炼金术》","url":"https://zh.wikipedia.org/wiki/乔治·索罗斯","date":"1987","topics":["市场","认知"],"skills":["poe-standard-answer","poe-decision","poe-verify"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"soros_02","knowledge":"市场永远有偏见：价格内含错误与不完整认知。商业启示：把『市场共识』当可证伪的假设而不是真理，共识错位处就是机会。","original":"乔治·索罗斯《金融炼金术》","url":"https://zh.wikipedia.org/wiki/乔治·索罗斯","date":"1987","topics":["市场","决策"],"skills":["poe-verify","poe-standard-answer","poe-decision"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"soros_03","knowledge":"繁荣-萧条周期：正反馈推动泡沫，反转时崩溃加速。商业启示：行业过热（融资金额、估值、扩产）本身就是风险信号，在别人贪婪时检查自己的退出机制。","original":"乔治·索罗斯《金融炼金术》","url":"https://zh.wikipedia.org/wiki/乔治·索罗斯","date":"1987","topics":["市场","风险"],"skills":["poe-standard-answer","poe-decision","poe-verify"],"type":"principle","confidence":"high","audience":"⚠️💼"},
{"id":"soros_04","knowledge":"易错性：人类认知天生有缺陷，我们对自己和世界的理解必然不完整。商业启示：给所有判断留『我可能错了』的余量，仓位、方案、承诺都要可逆。","original":"乔治·索罗斯《金融炼金术》","url":"https://zh.wikipedia.org/wiki/乔治·索罗斯","date":"1987","topics":["认知","决策"],"skills":["poe-verify","poe-decision","poe-good-question"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"soros_05","knowledge":"先活下来：生存优先于获利。商业启示：仓位管理第一原则——亏损超过承受线就必须离场，任何『这次不一样』都别信。","original":"乔治·索罗斯（投资实践）","url":"https://zh.wikipedia.org/wiki/乔治·索罗斯","date":"1987","topics":["风险","决策"],"skills":["poe-decision","poe-verify","poe-goal"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"soros_06","knowledge":"身体直觉：索罗斯用背部疼痛作为仓位风险信号。商业启示：长期浸泡某个领域后，身体反应是内隐知识的输出通道，重要决策前留意『不舒服感』。","original":"乔治·索罗斯（自述）","url":"https://zh.wikipedia.org/wiki/乔治·索罗斯","date":"1987","topics":["决策","心理"],"skills":["poe-decision","poe-action","poe-verify"],"type":"insight","confidence":"low","audience":"⚠️💼"},
{"id":"soros_07","knowledge":"反身性与基本面背离：当认知与现实互相强化到偏离基本面，拐点将至。商业启示：指标与叙事同向狂奔时（增长率、热度、估值），问一句『基本面跟上了吗』。","original":"乔治·索罗斯《金融炼金术》","url":"https://zh.wikipedia.org/wiki/乔治·索罗斯","date":"1987","topics":["市场","风险"],"skills":["poe-verify","poe-standard-answer","poe-decision"],"type":"principle","confidence":"medium","audience":"⚠️🔬"},
{"id":"soros_08","knowledge":"善用不确定：不确定性是机会的别名。商业启示：多数人厌恶不确定而回避，愿意研究不确定并下注的人获得风险溢价。","original":"乔治·索罗斯《金融炼金术》","url":"https://zh.wikipedia.org/wiki/乔治·索罗斯","date":"1987","topics":["决策","心态"],"skills":["poe-decision","poe-action","poe-slowisfast"],"type":"principle","confidence":"medium","audience":"⚠️💼"},

# ---------- 安迪·格鲁夫 ----------
{"id":"grove_01","knowledge":"只有偏执狂才能生存：成功会滋生自满，自满招致毁灭。商业启示：业绩最好的时候恰恰是最危险的时刻，持续疑神疑鬼地盯住环境变化。","original":"安迪·格鲁夫《只有偏执狂才能生存》","url":"https://zh.wikipedia.org/wiki/安迪·葛洛夫","date":"1996","topics":["战略","心态"],"skills":["poe-standard-answer","poe-decision","poe-verify"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"grove_02","knowledge":"战略转折点：当竞争、技术或用户出现10倍速变化，公司处于战略转折点。商业启示：识别『10倍速』信号（技术突破、规则改变、成本骤降），转折点不转身就会被拐弯甩下。","original":"安迪·格鲁夫《只有偏执狂才能生存》","url":"https://zh.wikipedia.org/wiki/安迪·葛洛夫","date":"1996","topics":["战略","创新"],"skills":["poe-standard-answer","poe-diagnosis","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"grove_03","knowledge":"中层感知：战略转折的早期信号常被中层最先感知，而非高层。商业启示：建立直达一线的信息通道（越级沟通、匿名反馈），高层别只依赖过滤过的汇报。","original":"安迪·格鲁夫《只有偏执狂才能生存》","url":"https://zh.wikipedia.org/wiki/安迪·葛洛夫","date":"1996","topics":["组织","决策"],"skills":["poe-diagnosis","poe-knowledge","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"grove_04","knowledge":"建设性对抗：直面问题、当面讲清，是高效组织文化。商业启示：回避冲突的文化会让问题烂在肚子里，建立『对事不对人』的当面沟通机制。","original":"安迪·格鲁夫《格鲁夫给经理人的第一课》","url":"https://zh.wikipedia.org/wiki/安迪·葛洛夫","date":"1983","topics":["组织","沟通"],"skills":["poe-diagnosis","poe-action","poe-goal"],"type":"method","confidence":"high","audience":"💼"},
{"id":"grove_05","knowledge":"产出导向管理：管理的产出是结果，不是活动量。商业启示：考核盯产出指标（交付、成果），别用加班时长、会议数量这类活动指标自我安慰。","original":"安迪·格鲁夫《格鲁夫给经理人的第一课》","url":"https://zh.wikipedia.org/wiki/安迪·葛洛夫","date":"1983","topics":["管理","激励"],"skills":["poe-goal","poe-diagnosis","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"grove_06","knowledge":"平台转换：技术平台的代际更替会颠覆在位者。商业启示：警惕『我们更懂技术』的傲慢，平台切换时旧优势可能全部作废，及早布局新平台能力。","original":"安迪·格鲁夫《只有偏执狂才能生存》","url":"https://zh.wikipedia.org/wiki/安迪·葛洛夫","date":"1996","topics":["战略","创新"],"skills":["poe-standard-answer","poe-diagnosis","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"grove_07","knowledge":"职业转折点：个人职业同样有战略转折点，要主动管理。商业启示：技能贬值、行业迁移是个人职业的10倍速变化，未雨绸缪地更新自己。","original":"安迪·格鲁夫《只有偏执狂才能生存》","url":"https://zh.wikipedia.org/wiki/安迪·葛洛夫","date":"1996","topics":["学习","心态"],"skills":["poe-learning","poe-decision","poe-goal"],"type":"principle","confidence":"high","audience":"🔥💼"},
{"id":"grove_08","knowledge":"制造即战略：生产能力本身是竞争武器。商业启示：别只盯营销与产品，供应链与制造环节的工艺优势是难被复制的护城河。","original":"安迪·格鲁夫《格鲁夫给经理人的第一课》","url":"https://zh.wikipedia.org/wiki/安迪·葛洛夫","date":"1983","topics":["运营","战略"],"skills":["poe-diagnosis","poe-standard-answer","poe-benchmark"],"type":"insight","confidence":"medium","audience":"💼"},
]
