# -*- coding: utf-8 -*-
"""扩展批次 P3：商业与行为决策思想家（芒格/卡尼曼/塞勒/塔勒布/德鲁克/波特/西蒙/科斯）"""

POWERS_P3 = [
# ---------- 查理·芒格 ----------
{"id":"munger_01","knowledge":"逆向思维：把问题倒过来想。多数人问『怎样成功』，芒格先问『怎样会死』。商业启示：重大决策先列失败清单，避开致命错误后再谈成功路径，比正面硬想更可靠。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["决策"],"skills":["poe-decision","poe-diagnosis","poe-verify"],"type":"method","confidence":"high","audience":"💼"},
{"id":"munger_02","knowledge":"多元思维模型：手里只有一把锤子，看什么都像钉子。商业启示：判断依赖单一学科必然失真，至少掌握数学、心理学、经济学、生物学的核心模型再下结论。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["决策","认知"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"munger_03","knowledge":"能力圈：只在圈内下注，圈外再诱人也放弃。商业启示：明确写出『我懂什么、我不懂什么』，能力圈的边界比大小重要，跨界自大会被市场教训。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["决策","战略"],"skills":["poe-decision","poe-goal","poe-diagnosis"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"munger_04","knowledge":"激励超级反应：人的行为几乎完全由激励驱动，且会为了激励做出疯狂的事。商业启示：设计激励时要问『这个规则会让所有人（包括我自己）做什么』，激励错位是组织乱象的头号来源。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["组织","激励"],"skills":["poe-diagnosis","poe-action","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"munger_05","knowledge":"误判心理学：人的决策系统性受社会认同、厌恶损失、过度乐观、服从权威等二十几种倾向扭曲。商业启示：先承认自己是易错机器，再建立对抗机制（清单、第三方视角、延迟决策）。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["心理","决策"],"skills":["poe-verify","poe-decision","poe-action"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"munger_06","knowledge":"耐心与集中：一生能做的重大决策没几次，少数几次重注优于频繁小赌。商业启示：把精力集中到少数高确信机会上，频繁切换等于反复付出交易成本。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["决策","心态"],"skills":["poe-decision","poe-slowisfast","poe-goal"],"type":"method","confidence":"medium","audience":"💼"},
{"id":"munger_07","knowledge":"长长的坡厚厚的雪：好生意要同时具备持续需求和复利特性。商业启示：评估业务先看坡的长度（市场生命周期）和雪的厚度（利润率与再投资回报），而不是眼前的增速。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["商业模式"],"skills":["poe-diagnosis","poe-standard-answer","poe-benchmark"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"munger_08","knowledge":"承认无知是智慧起点：说『我不知道』比假装知道值钱。商业启示：面对不确定问题，敢说不知道的人才能开始学习，装懂的人会一路错下去。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["决策","认知"],"skills":["poe-good-question","poe-decision","poe-verify"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"munger_09","knowledge":"避免愚蠢比追求聪明重要：剔除致命错误之后，平庸的表现也能赢。商业启示：防守型经营（不负债赌、不碰不懂的、不欺诈）长期回报高于进攻型聪明。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["决策","风险"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"munger_10","knowledge":"检查清单：重大决策用清单防遗漏。商业启示：飞行员靠清单不靠记忆，投融资、并购、发布等高风险决策同样要逐项核对关键条件，防止『我以为想到了』。","original":"查理·芒格《穷查理宝典》","url":"https://zh.wikipedia.org/wiki/查理·芒格","date":"2005","topics":["决策","组织"],"skills":["poe-decision","poe-good-question","poe-goal"],"type":"tool","confidence":"high","audience":"💼"},

# ---------- 丹尼尔·卡尼曼 ----------
{"id":"kahneman_01","knowledge":"双系统：系统1快而直觉，系统2慢而费力。商业启示：日常判断多数由系统1完成，重大决策必须主动唤醒系统2——把直觉结论当假设而不是答案。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["认知","决策"],"skills":["poe-decision","poe-verify","poe-good-question"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"kahneman_02","knowledge":"锚定效应：先出现的数字扭曲后续所有判断。商业启示：谈判、估值、定价先设理性锚，警惕对方抛出的第一个数字，也警惕自己心里的第一个数字。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["决策","心理","定价"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"kahneman_03","knowledge":"损失厌恶：同等金额的损失带来的痛苦约为收益快乐的2倍。商业启示：定价与方案设计要理解用户对『失去』的敏感，同时警惕自己因怕失去而做出防御性错误决策。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["心理","定价","决策"],"skills":["poe-resonate","poe-decision","poe-content"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"kahneman_04","knowledge":"可得性偏差：容易被想起的事被高估概率。商业启示：刚报道的危机、刚发生的爆款会扭曲风险判断，用数据校准『感觉概率』，别在恐慌或狂热时做决策。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["心理","决策","风险"],"skills":["poe-verify","poe-decision","poe-standard-answer"],"type":"anti-pattern","confidence":"high","audience":"🔬💼"},
{"id":"kahneman_05","knowledge":"过度自信：专家对自身判断的信心普遍远超准确率。商业启示：任何预测都要给出置信区间并记录预测理由，事后校准比事前感觉可靠。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["决策","认知"],"skills":["poe-verify","poe-decision","poe-ai-check"],"type":"anti-pattern","confidence":"high","audience":"🔬💼"},
{"id":"kahneman_06","knowledge":"框架效应：同一事实的不同表述改变选择。商业启示：给方案换三种说法自检，『存活率90%』和『死亡率10%』的信息价值相同但决策效果不同。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["心理","沟通","内容"],"skills":["poe-content","poe-deconstruct","poe-good-question"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"kahneman_07","knowledge":"峰终定律：体验记忆由峰值与结尾决定，而非全程平均。商业启示：产品与服务设计要制造记忆峰值和体面结尾，用户记住的是峰和终，不是琐碎的中间。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["产品","心理"],"skills":["poe-content","poe-resonate","poe-spread"],"type":"principle","confidence":"high","audience":"🔥💼"},
{"id":"kahneman_08","knowledge":"规划谬误：人系统性低估工期、成本与风险。商业启示：用参考类预测——找同类项目的实际历史数据做外部基准，替代内部乐观估计。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["决策","项目管理"],"skills":["poe-decision","poe-standard-answer","poe-verify"],"type":"anti-pattern","confidence":"high","audience":"💼"},
{"id":"kahneman_09","knowledge":"事前验尸：决策前假设它已经失败，然后倒推失败原因。商业启示：把『最坏情况』具象化为清单，能提前暴露被乐观掩盖的致命漏洞。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["决策","风险"],"skills":["poe-decision","poe-verify","poe-good-question"],"type":"method","confidence":"high","audience":"💼"},
{"id":"kahneman_10","knowledge":"回归均值：极端表现之后自然回落。商业启示：某月爆量、某人连续超预期，先问是能力还是运气，别在均值回归时把功劳当能力兑现。","original":"丹尼尔·卡尼曼《思考，快与慢》","url":"https://zh.wikipedia.org/wiki/丹尼尔·卡尼曼","date":"2011","topics":["决策","绩效"],"skills":["poe-decision","poe-standard-answer","poe-verify"],"type":"principle","confidence":"high","audience":"💼"},

# ---------- 理查德·塞勒 ----------
{"id":"thaler_01","knowledge":"心理账户：钱按来源与用途被分进不同心理账户。商业启示：定价与促销要理解用户把这笔消费放在哪个账户——省下的钱和赚到的钱对用户不是一回事。","original":"理查德·塞勒《错误的行为》","url":"https://zh.wikipedia.org/wiki/理查德·塞勒","date":"2015","topics":["心理","定价"],"skills":["poe-diagnosis","poe-content","poe-resonate"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"thaler_02","knowledge":"助推：默认选项就是决策。商业启示：把你想让人选的选项设为默认值，比发一百条通知更有效；同样，警惕平台默认选项正在替用户做决定。","original":"理查德·塞勒《助推》","url":"https://zh.wikipedia.org/wiki/理查德·塞勒","date":"2008","topics":["机制设计","心理"],"skills":["poe-diagnosis","poe-content","poe-decision"],"type":"method","confidence":"high","audience":"💼"},
{"id":"thaler_03","knowledge":"禀赋效应：一旦拥有，估值立刻升高。商业启示：试用期、体验装、先到先得利用的是『拥有感』，但谈判中也别高估自己手里的东西。","original":"理查德·塞勒《错误的行为》","url":"https://zh.wikipedia.org/wiki/理查德·塞勒","date":"2015","topics":["心理","营销"],"skills":["poe-content","poe-resonate","poe-spread"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"thaler_04","knowledge":"现值偏差：人对即时满足的贴现率远高于理性水平。商业启示：分期付款、先用后付让未来成本显得轻，做长期决策时要主动把未来收益折算回当下。","original":"理查德·塞勒《错误的行为》","url":"https://zh.wikipedia.org/wiki/理查德·塞勒","date":"2015","topics":["心理","定价","决策"],"skills":["poe-decision","poe-content","poe-resonate"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"thaler_05","knowledge":"沉没成本谬误：已投入的不该影响未来决策。商业启示：止损需要纪律，『已经投入这么多』不是继续投入的理由，问『从现在起』而非『从开始起』。","original":"理查德·塞勒《错误的行为》","url":"https://zh.wikipedia.org/wiki/理查德·塞勒","date":"2015","topics":["决策","心理"],"skills":["poe-decision","poe-action","poe-verify"],"type":"anti-pattern","confidence":"high","audience":"💼"},
{"id":"thaler_06","knowledge":"市场出清不等于个体最优：自由市场让资源流动，但个体照样犯系统性错误。商业启示：『市场会自我修正』不能替代对用户行为的直接研究。","original":"理查德·塞勒《错误的行为》","url":"https://zh.wikipedia.org/wiki/理查德·塞勒","date":"2015","topics":["市场","心理"],"skills":["poe-verify","poe-diagnosis","poe-standard-answer"],"type":"insight","confidence":"medium","audience":"🔬💼"},
{"id":"thaler_07","knowledge":"行为矫正设计：让正确选择成为最省力的选择。商业启示：别指望意志力，把健康、储蓄、合规等目标嵌进流程默认值，比动员大会有效。","original":"理查德·塞勒《助推》","url":"https://zh.wikipedia.org/wiki/理查德·塞勒","date":"2008","topics":["组织","机制设计"],"skills":["poe-diagnosis","poe-action","poe-goal"],"type":"method","confidence":"high","audience":"💼"},
{"id":"thaler_08","knowledge":"损失框架比收益框架更能推动行动：医疗、环保、绩效沟通中『失去什么』比『得到什么』更有力量。商业启示：劝服性文案先测试损失框架，但要承担道德责任。","original":"理查德·塞勒《助推》","url":"https://zh.wikipedia.org/wiki/理查德·塞勒","date":"2008","topics":["内容","心理"],"skills":["poe-content","poe-hook","poe-resonate"],"type":"principle","confidence":"medium","audience":"🔥💼"},

# ---------- 纳西姆·塔勒布 ----------
{"id":"taleb_01","knowledge":"黑天鹅：罕见高冲击事件主导历史，而正态分布思维对此完全失灵。商业启示：用『黑天鹅会来』做压力测试的底线假设，不要用平均值规划生死攸关的事。","original":"纳西姆·塔勒布《黑天鹅》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2007","topics":["风险","决策"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"principle","confidence":"medium","audience":"⚠️🔬"},
{"id":"taleb_02","knowledge":"反脆弱：有些系统在波动中获益。商业启示：设计业务时加入冗余、可逆选项与小步试错，让意外成为养分而不是灾难。","original":"纳西姆·塔勒布《反脆弱》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2012","topics":["风险","组织","战略"],"skills":["poe-diagnosis","poe-decision","poe-standard-answer"],"type":"principle","confidence":"medium","audience":"⚠️💼"},
{"id":"taleb_03","knowledge":"杠铃策略：极度保守与极度冒险并存，放弃中庸。商业启示：大部分资产放在安全端，小部分下注高赔率机会，中间地带最脆弱。","original":"纳西姆·塔勒布《反脆弱》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2012","topics":["决策","风险"],"skills":["poe-decision","poe-slowisfast","poe-verify"],"type":"method","confidence":"medium","audience":"⚠️💼"},
{"id":"taleb_04","knowledge":"绿木谬误：新手总想预测未来，老手关注下行风险。商业启示：问『最坏能亏多少、我能否承受』比问『会涨多少』优先，先活下来再谈收益。","original":"纳西姆·塔勒布《随机漫步的傻瓜》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2001","topics":["风险","决策"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"anti-pattern","confidence":"high","audience":"💼"},
{"id":"taleb_05","knowledge":"叙事谬误：事后编的故事让随机事件显得可预测。商业启示：复盘时要区分『机制解释』与『叙事自洽』，能讲得通不代表本来就能预见。","original":"纳西姆·塔勒布《黑天鹅》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2007","topics":["决策","认知"],"skills":["poe-verify","poe-decision","poe-deconstruct"],"type":"anti-pattern","confidence":"high","audience":"🔬💼"},
{"id":"taleb_06","knowledge":"幸存者偏差：只看到活下来的样本，会系统性高估成功概率。商业启示：研究失败案例与退出者的数据，别只向成功者取经。","original":"纳西姆·塔勒布《随机漫步的傻瓜》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2001","topics":["决策","认知","benchmark"],"skills":["poe-verify","poe-benchmark","poe-standard-answer"],"type":"anti-pattern","confidence":"high","audience":"🔬💼"},
{"id":"taleb_07","knowledge":"做减法比做加法难：移除噪声比增加信号更有效。商业启示：产品、流程、汇报先删再增，臃肿是默认态，精简是刻意为之。","original":"纳西姆·塔勒布《反脆弱》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2012","topics":["产品","组织"],"skills":["poe-diagnosis","poe-deconstruct","poe-good-question"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"taleb_08","knowledge":"少即是多（信息）：大量无关信息降低决策质量。商业启示：给决策者喂干净的信号，指标数量超过七个就开始互相掩盖。","original":"纳西姆·塔勒布《黑天鹅》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2007","topics":["决策","信息"],"skills":["poe-good-question","poe-decision","poe-ai-check"],"type":"principle","confidence":"medium","audience":"💼"},
{"id":"taleb_09","knowledge":"尾部风险：关注小概率大损失，而非平均情况。商业启示：保险、库存、现金流都要按尾部事件设计，平均数是和平年代的统计幻觉。","original":"纳西姆·塔勒布《反脆弱》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2012","topics":["风险","决策"],"skills":["poe-decision","poe-verify","poe-diagnosis"],"type":"method","confidence":"medium","audience":"⚠️💼"},
{"id":"taleb_10","knowledge":"林迪效应：已经存续很久的事物，预期还能存续更久。商业启示：选择技术栈、商业模式、内容形式时，长寿性本身是信息，新不代表好。","original":"纳西姆·塔勒布《反脆弱》","url":"https://zh.wikipedia.org/wiki/納西姆·尼可拉斯·塔勒布","date":"2012","topics":["决策","战略"],"skills":["poe-standard-answer","poe-decision","poe-benchmark"],"type":"principle","confidence":"medium","audience":"⚠️💼"},

# ---------- 彼得·德鲁克 ----------
{"id":"drucker_01","knowledge":"管理的本质：让平凡人做出不平凡的事。商业启示：管理的成就不在管理者多优秀，而在组织能否放大普通人的产出。","original":"彼得·德鲁克《管理的实践》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1954","topics":["组织","管理"],"skills":["poe-diagnosis","poe-action","poe-standard-answer"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"drucker_02","knowledge":"目标管理：先定义要达成的成果，再分配资源与责任。商业启示：目标模糊时一切执行都是浪费，先写清『成功长什么样、谁负责、何时交付』。","original":"彼得·德鲁克《管理的实践》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1954","topics":["组织","目标管理"],"skills":["poe-goal","poe-decision","poe-good-question"],"type":"method","confidence":"high","audience":"💼"},
{"id":"drucker_03","knowledge":"知识工作者：产出无法直接观察，管理靠目标与信任而非盯过程。商业启示：对脑力劳动者按成果付酬与评价，盯考勤只会得到『人在心不在』。","original":"彼得·德鲁克《卓有成效的管理者》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1967","topics":["组织","管理"],"skills":["poe-diagnosis","poe-action","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"drucker_04","knowledge":"有效管理者从时间管理开始：记录、削减、合并自己的时间。商业启示：先记录一周时间去向再谈效率，多数人的『忙』经不起时间账本检验。","original":"彼得·德鲁克《卓有成效的管理者》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1967","topics":["管理","心态"],"skills":["poe-action","poe-slowisfast","poe-decision"],"type":"method","confidence":"high","audience":"💼"},
{"id":"drucker_05","knowledge":"贡献导向：问『我能贡献什么』而非『我能得到什么』。商业启示：晋升与影响力来自可衡量的贡献，聚焦贡献的人自动获得组织信任。","original":"彼得·德鲁克《卓有成效的管理者》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1967","topics":["组织","心态"],"skills":["poe-action","poe-goal","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"drucker_06","knowledge":"顾客决定企业：企业存在的目的是创造顾客，利润是结果不是目的。商业启示：商业模式叙事必须以顾客价值为起点，利润只是价值创造的回报凭证。","original":"彼得·德鲁克《管理的实践》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1954","topics":["商业模式","战略"],"skills":["poe-diagnosis","poe-standard-answer","poe-good-question"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"drucker_07","knowledge":"系统化创新：创新来自对变化的警觉而非灵感。商业启示：定期扫描人口、认知、技术、行业结构的意外变化，创新机会藏在变化里。","original":"彼得·德鲁克《创新与企业家精神》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1985","topics":["创新","战略"],"skills":["poe-standard-answer","poe-diagnosis","poe-benchmark"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"drucker_08","knowledge":"决策五要素：问题分类、定义问题、明确边界、执行路径、反馈闭环。商业启示：跳过前两步直接谈方案的会议，多数在讨论错误的问题。","original":"彼得·德鲁克《卓有成效的管理者》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1967","topics":["决策"],"skills":["poe-good-question","poe-decision","poe-goal"],"type":"method","confidence":"high","audience":"💼"},
{"id":"drucker_09","knowledge":"要事优先：集中资源于少数大事，同时放弃次要事。商业启示：『重要但没空』是资源错配的委婉说法，优先级是砍出来的不是排出来的。","original":"彼得·德鲁克《卓有成效的管理者》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1967","topics":["管理","决策"],"skills":["poe-goal","poe-slowisfast","poe-action"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"drucker_10","knowledge":"摆脱过去：放弃旧业务是增长的前提。商业启示：组织被历史包袱拖慢时，『停止做什么』和『开始做什么』同等重要。","original":"彼得·德鲁克《卓有成效的管理者》","url":"https://zh.wikipedia.org/wiki/彼得·德鲁克","date":"1967","topics":["战略","组织"],"skills":["poe-diagnosis","poe-decision","poe-action"],"type":"insight","confidence":"high","audience":"💼"},

# ---------- 迈克尔·波特 ----------
{"id":"porter_01","knowledge":"五力模型：行业吸引力由供应商议价力、买方议价力、新进入者威胁、替代品威胁、现有竞争强度五种力量决定。商业启示：分析行业先画五力，力量越强利润越薄。","original":"迈克尔·波特《竞争战略》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1980","topics":["战略","商业模式"],"skills":["poe-diagnosis","poe-standard-answer","poe-benchmark"],"type":"tool","confidence":"high","audience":"💼"},
{"id":"porter_02","knowledge":"三种通用战略：成本领先、差异化、聚焦，夹在中间最危险。商业启示：明确自己是靠便宜、靠独特还是靠细分活，两头都想要通常两头都得不到。","original":"迈克尔·波特《竞争战略》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1980","topics":["战略"],"skills":["poe-diagnosis","poe-standard-answer","poe-benchmark"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"porter_03","knowledge":"价值链：竞争优势藏在活动的链条里。商业启示：逐环节审视自己的价值链，找成本与差异化的真正来源，别只在终端拼价格。","original":"迈克尔·波特《竞争优势》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1985","topics":["战略","运营"],"skills":["poe-diagnosis","poe-decision","poe-benchmark"],"type":"tool","confidence":"high","audience":"💼"},
{"id":"porter_04","knowledge":"战略是选择不做什么：运营效益≠战略，无取舍无战略。商业启示：什么都做只是更快地同质化，战略的价值在于让一些客户满意地『不是你』。","original":"迈克尔·波特《什么是战略》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1996","topics":["战略"],"skills":["poe-diagnosis","poe-goal","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"porter_05","knowledge":"定位：在利润池中占据有利位置。商业启示：市场空间≠利润空间，分析各环节的利润分布，把资源压到利润最厚的环节。","original":"迈克尔·波特《竞争优势》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1985","topics":["战略","商业模式"],"skills":["poe-diagnosis","poe-benchmark","poe-standard-answer"],"type":"method","confidence":"high","audience":"💼"},
{"id":"porter_06","knowledge":"进入壁垒：来自规模经济、转换成本、网络效应与资源壁垒。商业启示：评估生意先问『壁垒在哪』，没有壁垒的规模只是暂时领先。","original":"迈克尔·波特《竞争战略》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1980","topics":["战略","商业模式"],"skills":["poe-diagnosis","poe-standard-answer","poe-benchmark"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"porter_07","knowledge":"相关性多元化：进入与主业共享价值链的新业务，成功率高；无关联多元化多失败。商业启示：扩张前问『新业务复用了我哪些核心活动』。","original":"迈克尔·波特《竞争优势》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1985","topics":["战略","商业模式"],"skills":["poe-diagnosis","poe-decision","poe-standard-answer"],"type":"insight","confidence":"high","audience":"💼"},
{"id":"porter_08","knowledge":"战略连续性：好战略需要十年一贯的执行。商业启示：频繁改战略等于没有战略，把择时与坚持分开——选对后靠纪律兑现。","original":"迈克尔·波特《什么是战略》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1996","topics":["战略","心态"],"skills":["poe-slowisfast","poe-goal","poe-decision"],"type":"principle","confidence":"medium","audience":"💼"},
{"id":"porter_09","knowledge":"竞争不是零和：价值创造型战略扩大蛋糕，争夺型战略分蛋糕。商业启示：先问自己是否在创造新价值，纯粹的价格绞杀是行业性自杀。","original":"迈克尔·波特《竞争优势》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1985","topics":["战略","市场"],"skills":["poe-diagnosis","poe-standard-answer","poe-benchmark"],"type":"principle","confidence":"medium","audience":"💼"},
{"id":"porter_10","knowledge":"集群竞争：地理集群（硅谷、义乌）通过共享要素与知识溢出提升生产率。商业启示：选址与生态选择要考虑集群效应，单打独斗对抗集群很难。","original":"迈克尔·波特《国家竞争优势》","url":"https://zh.wikipedia.org/wiki/迈克尔·波特","date":"1990","topics":["战略","市场"],"skills":["poe-diagnosis","poe-benchmark","poe-standard-answer"],"type":"insight","confidence":"medium","audience":"💼"},

# ---------- 赫伯特·西蒙 ----------
{"id":"simon_01","knowledge":"有限理性：人只有有限信息与算力，决策不可能是完全理性的。商业启示：承认决策的最优解不可得，把精力放在改善决策过程而非幻想完美判断。","original":"赫伯特·西蒙《管理行为》","url":"https://zh.wikipedia.org/wiki/赫伯特·西蒙","date":"1947","topics":["决策","认知"],"skills":["poe-decision","poe-good-question","poe-verify"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"simon_02","knowledge":"满意化：找到『够好』的选项就停。商业启示：大多数决策不值得追求最优，设定可接受标准然后行动，把剩余精力留给真正重大的决策。","original":"赫伯特·西蒙《管理行为》","url":"https://zh.wikipedia.org/wiki/赫伯特·西蒙","date":"1947","topics":["决策"],"skills":["poe-decision","poe-goal","poe-action"],"type":"method","confidence":"high","audience":"💼"},
{"id":"simon_03","knowledge":"专业直觉是模式识别：专家直觉=长期训练后对情境的快速组块识别。商业启示：直觉可靠的前提是该领域有稳定规律且你训练足够，否则直觉只是偏见。","original":"赫伯特·西蒙《管理行为》","url":"https://zh.wikipedia.org/wiki/赫伯特·西蒙","date":"1947","topics":["决策","认知"],"skills":["poe-verify","poe-decision","poe-action"],"type":"principle","confidence":"high","audience":"🔬💼"},
{"id":"simon_04","knowledge":"组织是注意力分配器：组织行为取决于注意力投向何处。商业启示：你奖励什么、汇报什么、会议讨论什么，就是组织在分配注意力，这决定了组织做什么。","original":"赫伯特·西蒙《管理行为》","url":"https://zh.wikipedia.org/wiki/赫伯特·西蒙","date":"1947","topics":["组织","管理"],"skills":["poe-diagnosis","poe-action","poe-decision"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"simon_05","knowledge":"层级系统：复杂系统由多层级分解才可管理。商业启示：把大问题分解成可独立解决的子问题，层级化是复杂组织的唯一出路。","original":"赫伯特·西蒙《人工科学》","url":"https://zh.wikipedia.org/wiki/赫伯特·西蒙","date":"1969","topics":["组织","决策"],"skills":["poe-good-question","poe-decision","poe-diagnosis"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"simon_06","knowledge":"搜索空间：问题解决=在可能的方案空间里启发式搜索。商业启示：先明确方案空间边界再求解，找不到答案常常因为搜索空间本身画错了。","original":"赫伯特·西蒙《人类问题解决》","url":"https://zh.wikipedia.org/wiki/赫伯特·西蒙","date":"1972","topics":["决策","认知"],"skills":["poe-good-question","poe-decision","poe-deconstruct"],"type":"method","confidence":"medium","audience":"🔬💼"},
{"id":"simon_07","knowledge":"决策前提：组织决策由一系列前提构成。商业启示：管理前提（信息、规则、价值观）比管理决策本身更根本，改前提比逐个改决策高效。","original":"赫伯特·西蒙《管理行为》","url":"https://zh.wikipedia.org/wiki/赫伯特·西蒙","date":"1947","topics":["组织","管理"],"skills":["poe-diagnosis","poe-decision","poe-action"],"type":"principle","confidence":"medium","audience":"💼"},
{"id":"simon_08","knowledge":"有限注意是稀缺资源：信息爆炸的真正瓶颈是注意力。商业启示：给团队的信息不是越多越好，组织真正的稀缺品是高质量注意力。","original":"赫伯特·西蒙《管理行为》","url":"https://zh.wikipedia.org/wiki/赫伯特·西蒙","date":"1947","topics":["组织","信息"],"skills":["poe-good-question","poe-decision","poe-ai-check"],"type":"principle","confidence":"high","audience":"💼"},

# ---------- 罗纳德·科斯 ----------
{"id":"coase_01","knowledge":"交易成本：企业之所以存在，是因为通过市场完成交易的成本太高。商业启示：凡是市场摩擦大的环节就有商业模式的机会，减少交易成本本身就是生意。","original":"罗纳德·科斯《企业的性质》","url":"https://zh.wikipedia.org/wiki/罗纳德·科斯","date":"1937","topics":["商业模式","市场"],"skills":["poe-diagnosis","poe-standard-answer","poe-good-question"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"coase_02","knowledge":"企业边界：自建还是外包，取决于内部组织成本与市场交易成本的比较。商业启示：边界不是战略偏好，是成本比较的结论，AI 时代交易成本变化会重画企业边界。","original":"罗纳德·科斯《企业的性质》","url":"https://zh.wikipedia.org/wiki/罗纳德·科斯","date":"1937","topics":["组织","战略"],"skills":["poe-diagnosis","poe-decision","poe-standard-answer"],"type":"principle","confidence":"high","audience":"💼"},
{"id":"coase_03","knowledge":"科斯定理：产权清晰且交易成本为零时，外部性问题可由双方自行谈判解决。商业启示：多数外部性纠纷源于产权界定不清，先把『谁拥有什么』写清楚。","original":"罗纳德·科斯《社会成本问题》","url":"https://zh.wikipedia.org/wiki/罗纳德·科斯","date":"1960","topics":["市场","机制设计"],"skills":["poe-verify","poe-diagnosis","poe-deconstruct"],"type":"principle","confidence":"medium","audience":"⚠️🔬"},
{"id":"coase_04","knowledge":"社会成本问题：外部性的本质是产权界定与交易安排问题，而不是简单的『加害者赔偿』。商业启示：谈责任之前先谈权利边界，权利不清则责任无从谈起。","original":"罗纳德·科斯《社会成本问题》","url":"https://zh.wikipedia.org/wiki/罗纳德·科斯","date":"1960","topics":["市场","机制设计"],"skills":["poe-deconstruct","poe-diagnosis","poe-verify"],"type":"principle","confidence":"medium","audience":"🔬💼"},
{"id":"coase_05","knowledge":"交易成本决定平台价值：平台本质是降低双边匹配的交易成本。商业启示：评估平台生意看它把哪类交易成本从高降到低，降幅即价值。","original":"罗纳德·科斯《企业的性质》","url":"https://zh.wikipedia.org/wiki/罗纳德·科斯","date":"1937","topics":["商业模式","市场"],"skills":["poe-diagnosis","poe-standard-answer","poe-benchmark"],"type":"insight","confidence":"medium","audience":"💼"},
{"id":"coase_06","knowledge":"契约不完备：现实契约无法穷尽所有未来情况。商业启示：合作的关键不在合同写得多细，而在争议出现时的关系与信任，关系是契约的补丁。","original":"罗纳德·科斯《企业的性质》","url":"https://zh.wikipedia.org/wiki/罗纳德·科斯","date":"1937","topics":["组织","决策"],"skills":["poe-decision","poe-deconstruct","poe-good-question"],"type":"insight","confidence":"medium","audience":"💼"},
]
